services:
  web_client:
    build:
      context: .
      dockerfile: ./dossier_client/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./dossier_client:/app
      - ./crypto_utils.py:/app/crypto_utils.py
    environment:
      - FLASK_LDAP_HOST=ldap://ldap:389
      - FLASK_LDAP_BASE_DN=dc=td,dc=anthonymoll,dc=fr
      - FLASK_LDAP_USER_DN=ou=users
      - FLASK_LDAP_BIND_USER_DN=cn=admin,dc=td,dc=anthonymoll,dc=fr
      - FLASK_LDAP_BIND_USER_PASSWORD=adminpassword
      - ADMIN_USERNAME=admin
    networks:
      - auth_net

  storage_server:
    build:
      context: .
      dockerfile: ./dossier_server/Dockerfile
    ports:
      - "65432:65432"
    volumes:
      - ./dossier_server:/app
      - storage_data:/app/storage
    networks:
      - auth_net

volumes:
  storage_data:

networks:
  auth_net:
    external: true
