services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap-server
    restart: unless-stopped
    environment:
      LDAP_ORGANISATION: "${LDAP_ORGANISATION}"
      LDAP_DOMAIN: "${LDAP_DOMAIN}"
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD}"
    ports:
      - "${LDAP_PORT}:389"
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d
      # CHARGEMENT CORRECT DU LDIF DE BOOTSTRAP
      - ./init:/container/service/slapd/assets/config/bootstrap/ldif/custom
    networks:
      - auth_net

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    restart: unless-stopped
    environment:
      PHPLDAPADMIN_HTTPS: "${PHPLDAPADMIN_HTTPS}"
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      LDAP_ADMIN_LOGIN: "${LDAP_ADMIN_LOGIN}"
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD}"
    ports:
      - "${PHPLDAPADMIN_PORT}:80"
    volumes:
      - ./config:/etc/phpldapadmin/config
    networks:
      - auth_net

  php-app:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: php-app
    restart: unless-stopped
    volumes:
      - ./www:/var/www/html
    ports:
      - "${PHP_APP_PORT}:80"
    networks:
      - auth_net

volumes:
  ldap-data:
  ldap-config:

networks:
  auth_net:
    external: true
